##################################################
# +--------------------------------------------+ #
# |                kEssentials                 | #
# +--------------------------------------------+ #
##################################################

# Should players see the MOTD when they log in?
motd-on-login: true

# What should the cooldown be on /heal (in seconds)
heal-cooldown: 60




##################################################
# +--------------------------------------------+ #
# |                   kChat                    | #
# +--------------------------------------------+ #
##################################################

# What color should an op's name be? Set to 'none' for no change
op-name-color: '&c'

# Should color symbols be allowed in the chat?
colors-allowed-chat: true

# How far away from the player should messages be "heard" from?
# Set to 0 for infinite (vanilla minecraft)
chat-radius: 100

# Do you want to use the kChat spam blocker?
use-spam-blocker: true




##################################################
# +--------------------------------------------+ #
# |                  kEconomy                  | #
# +--------------------------------------------+ #
##################################################

# This is the amount of money that players start with
starting-balance: 30

# This is what will be displayed with money ($10)
currency-symbol: '$'

# Changes in players' money will be logged
log-economy-data: true