name: kEssentials
main: me.KeybordPiano459.kEssentials.kEssentials
version: 1.0

commands:
  back:
    description: Teleport to your last location
    aliases: [kback]
  backpack:
    description: Open a personal backpack
    aliases: [kbackpack]
  butcher:
    description: Kill all nearby mobs
    aliases: [kbutcher]
  clearenderchest:
    description: Clear your entire ender chest
    aliases: [ce, kce, kclearenderchest]
  clearinventory:
    description: Clear your entire inventory
    aliases: [ci, kci, kclearinventory]
  day:
    description: Make it daytime in your world
    aliases: [daytime, kday, kdaytime]
  delwarp:
    description: Delete an already set warp
    aliases: [deletewarp, kdeletewarp, kdelwarp]
  enderchest:
    description: View someone's enderchest
    aliases: [viewender, seeender, kenderchest, kseeender, kviewender]
  garbagecollector:
    description: Run the Java garbage collector
    aliases: [gc, kgarbagecollector, kgc]
  getid:
    description: Get the ID of what you're holding
    aliases: [handid, kgetid, khandid]
  god:
    description: Make yourself invincible!
    aliases: [invincible, kgod, kinvincible]
  hat:
    description: Wear a block on your head
    aliases: [khat]
  home:
    description: Teleport to your home
    aliases: [khome]
  ignite:
    description: Set someone on fire
    aliases: [burn, kburn, kignite]
  itemname:
    description: Name the item in your hand
    aliases: [nameitem, kitemname, knameitem]
#  kessentials:
#    description: Various actions related to kEssentials
#    aliases: [kes]
  me:
    description: Perform an action in the chat
    aliases: [action, kaction, kme]
  motd:
    description: See the message of the day
    aliases: [kmotd]
  mute:
    description: Make it so that someone can't chat
    aliases: [silence, kmute, ksilence]
#  myhead:
#    description: Get your very own head
#    aliases: [head, khead, kmyhead]
  night:
    description: Make it nighttime in your world
    aliases: [nighttime, knight, knighttime]
  online:
    description: Check if a player is online
    aliases: [offline, koffline, konline]
  ping:
    description: Useful to check if you're lagging
    aliases: [pong, kping, kpong]
  rain:
    description: Turn on a storm in your world
    aliases: [storm, kstorm, krain]
  ram:
    description: See the server's RAM usage
    aliases: [speed, kram, kspeed]
  remove:
    description: Remove nearby entities
    aliases: [kremove]
  repair:
    description: Repair the item in your hand
    aliases: [krepair]
  rules:
    description: View the server rules
    aliases: [krules]
  sethome:
    description: Set your home
    aliases: [ksethome]
  setspawn:
    description: Set the server spawn
    aliases: [ksetspawn]
  setwarp:
    description: Set a warp location
    aliases: [ksetwarp]
  spawn:
    description: Teleport to the server spawn
    aliases: [kspawn]
  spawner:
    description: Change a spawner's mob type
    aliases: [kspawner]
  suicide:
    description: Take a guess...
    aliases: [ksuicide]
  sun:
    description: Turn the weather off in your world
    aliases: [ksun]
  tps:
    description: Check the server's TPS rate
    aliases: [ktps]
  ungod:
    description: Make yourself vulnerable again
    aliases: [vulnerable, kungod, kvulnerable]
  unmute:
    description: Un-mute a person
    aliases: [unsilence, kunmute, kunsilence]
  warp:
    description: Warp to a set location
    aliases: [kwarp]
  warplist:
    description: List all set warps
    aliases: [wl, kwarplist, kwl]
  workbench:
    description: Open up a crafting table
    aliases: [craft, kcraft, kworkbench]
#  worldtime:
#    description: See the time on the server computer
#    aliases: [kworldtime]

permissions:
  kessentials.*:
    description: All permissions
    default: op
    children:
      kessentials.back: true
      kessentials.backpack: true
      kessentials.butcher: true
      kessentials.clearenderchest.*: true
      kessentials.clearinventory.*: true
      kessentials.day: true
      kessentials.delwarp: true
      kessentials.enderchest.*: true
      kessentials.garbagecollector: true
      kessentials.getid: true
      kessentials.god: true
      kessentials.hat: true
      kessentials.home: true
      kessentials.ignite.*: true
      kessentials.itemname: true
      kessentials.motd: true
      kessentials.mute: true
#      kessentials.myhead: true
      kessentials.night: true
      kessentials.online: true
      kessentials.ping: true
      kessentials.rain: true
      kessentials.ram: true
      kessentials.remove: true
      kessentials.repair: true
      kessentials.rules: true
      kessentials.sethome: true
      kessentials.setspawn: true
      kessentials.setwarp: true
      kessentials.spawn: true
      kessentials.spawner: true
      kessentials.suicide: true
      kessentials.sun: true
      kessentials.tps: true
      kessentials.ungod: true
      kessentials.unmute: true
      kessentials.warp: true
      kessentials.warplist: true
      kessentials.workbench: true
#      kessentials.worldtime: true
  kessentials.back:
    description: /back
    default: op
  kessentials.backpack:
    description: /backpack
    default: op
  kessentials.day:
    description: /day
    default: op
  kessentials.delwarp:
    description: /delwarp <warp>
    default: op
  kessentials.garbagecollector:
    description: /garbagecollector
    default: true
  kessentials.getid:
    description: /getid
    default: true
  kessentials.god:
    description: /god
    default: op
  kessentials.hat:
    description: /hat
    default: op
  kessentials.home:
    description: /home
    default: true
  kessentials.itemname:
    description: /itemname <name>
    default: op
  kessentials.motd:
    description: /motd
    default: true
  kessentials.mute:
    description: /mute <player>
    default: op
#  kessentials.myhead:
#    description: /myhead
#    default: op
  kessentials.night:
    description: /night
    default: op
  kessentials.online:
    description: /online <player>
    default: true
  kessentials.ping:
    description: /ping
    default: true
  kessentials.rain:
    description: /rain
    default: op
  kessentials.ram:
    description: /ram
    default: true
  kessentials.remove:
    description: /remove <all|arrows|boats|items|minecarts|paintings> <radius>
    default: op
  kessentials.repair:
    description: /repair
    default: op
  kessentials.rules:
    description: /rules
    default: true
  kessentials.sethome:
    description: /sethome
    default: true
  kessentials.setspawn:
    description: /setspawn
    default: op
  kessentials.setwarp:
    description: /setwarp
    default: op
  kessentials.spawn:
    description: /spawn
    default: true
  kessentials.spawner:
    description: /spawner
    default: op
  kessentials.suicide:
    description: /suicide
    default: true
  kessentials.sun:
    description: /sun
    default: op
  kessentials.tps:
    description: /tps
    default: true
  kessentials.ungod:
    description: /ungod
    default: op
  kessentials.unmute:
    description: /unmute <player>
    default: op
  kessentials.warp:
    description: /warp
    default: true
  kessentials.warplist:
    description: /warplist
    default: true
  kessentials.workbench:
    description: /workbench
    default: op
#  kessentials.worldtime:
#    description: /worldtime
#    default: true

  kessentials.clearenderchest.*:
    description: All clearenderchest permissions
    default: op
    children:
      kessentials.clearenderchest.others: true
      kessentials.clearenderchest.self: true
  kessentials.clearenderchest.others:
    description: /clearenderchest [player]
    default: op
  kessentials.clearenderchest.self:
    description: /clearenderchest
    default: true

  kessentials.clearinventory.*:
    description: All clearinventory permissions
    default: op
    children:
      kessentials.clearinventory.others: true
      kessentials.clearinventory.self: true
  kessentials.clearinventory.others:
    description: /clearinventory [player]
    default: op
  kessentials.clearinventory.self:
    description: /clearinventory
    default: true

  kessentials.enderchest.*:
    description: All enderchest permissions
    default: op
    children:
      kessentials.enderchest.others: true
      kessentials.enderchest.self: true
  kessentials.enderchest.others:
    description: /enderchest [player]
    default: op
  kessentials.enderchest.self:
    description: /enderchest
    default: op

  kessentials.ignite.*:
    description: All ignite permissions
    default: op
    children:
      kessentials.ignite.others: true
      kessentials.ignite.self: true
  kessentials.ignite.others:
    description: /ignite [player]
    default: op
  kessentials.ignite.self:
    description: /ignite
    default: true